import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import {MantineProvider} from "@mantine/core";
import { DatesProvider } from '@mantine/dates';
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import '@mantine/dates/styles.css';


const geistSans =  Plus_Jakarta_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
      <MantineProvider>
          <DatesProvider settings={{ locale: 'en', firstDayOfWeek: 0 }}>
        {children}
          </DatesProvider>
      </MantineProvider>
      </body>
    </html>
  );
}
